{% set version = "0.27.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qs/qs_{{ version }}.tar.gz
  sha256: ed27ebee27f37289ec1cc141134e785aeba61a2c8b9c83b463597bc17e9fab01

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rapiserialize >=0.1.1
    - r-rcpp
    - r-stringfish >=0.15.1
    - lz4-c
    - zstd
  run:
    - r-base
    - r-rapiserialize >=0.1.1
    - r-rcpp
    - r-stringfish >=0.15.1

test:
  commands:
    - $R -e "library('qs')"           # [not win]
    - "\"%R%\" -e \"library('qs')\""  # [win]

about:
  home: https://github.com/traversc/qs
  license: GPL-3.0-only
  summary: Provides functions for quickly writing and reading any R object to and from disk.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
